#!/bin/bash
dir=${BASH_SOURCE%/*} 
if [ $# -eq 0 ]
    then
        printf "Usage <script>
    Options:
        r: run
        u: upload
        t: terminal            
    Commands:
        run [.lua-file]
        upload [.lua-file]
        terminal ([.lua-file] to run file from terminal)\n"
else
    if [ "$1" = "r" ];
        then
            if [[ $2 = "" ]];
                then
                sh $dir/nodemcu_run
            else
                sh $dir/nodemcu_run $2
            fi
    elif [ "$1" = "u" ];
        then 
            if [[ $2 = "" ]];
                then
                    sh $dir/nodemcu_upload
            else
                sh $dir/nodemcu_upload $2

            fi
    elif [ "$1" = "t" ];
        then
            if [[ $2 = "" ]];
                then
                sh $dir/nodemcu_terminal
            else
                sh $dir/nodemcu_terminal --run $2
            fi
    fi

fi
