FROM node:16 AS build-stage

WORKDIR /app

# copy frontend to /app
COPY ../. .

#install dependencies
RUN yarn install --silent

#build production app
RUN yarn run build:production

FROM nginx:alpine

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY --from=build-stage /app/.config/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
