version: '3.5'
services:
  frontend:
    stdin_open: true
    image: ghcr.io/fredrikmorstad/plants-meet-internet/frontend-production:latest
    container_name: plants_frontend
    ports:
        - 80:80
