FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

WORKDIR /app
ADD requirements.txt /app
COPY . .
RUN mkdir db
RUN pip3 install --upgrade pip
RUN pip3 install pipenv
RUN pip3 install -r requirements.txt

EXPOSE 5000
CMD ["python3", "manage.py"]
