version: "3.5"
services:
  production:
    image: ghcr.io/fredrikmorstad/docker-test/prod-api:latest
    ports:
        - "4000:5000"
    volumes:
        - ../db/prod-plant_db.sqlite3:/app/db/prod-plant_db.sqlite3
    environment:
        API_VERSION: 'prod'

