version: "3.5"
services:
  dev:
    build: 
      context: ..
      dockerfile: .docker/dockerfile
    ports:
      - "3000:5000"
    volumes:
        - ../db/dev-plant_db.sqlite3:/app/db/dev-plant_db.sqlite3
    environment:
        API_VERSION: 'dev'

