name: Build and push API-image
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: docker/login-action@v1
      with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
          context: ./backend
          push: true
          file: backend/.docker/dockerfile
          tags: ghcr.io/fredrikmorstad/plants-meet-internet/prod-api:latest
